import { jsPDF } from "jspdf";
import { EMBLEM_BASE64 } from "./emblemBase64";

export interface EtaData {
  applicationId?: string;
  fullName?: string;
  passportNumber?: string;
  nationality?: string;
  gender?: string;
  dob?: string;
  stay?: string;
  visaType?: string;
  applicationType?: string;
  issueDate?: string;
  expiryDate?: string;
  entries?: string;
  status?: string;
}

export function generateEtaPdf(data: EtaData = {}) {
  const {
    applicationId = "ETV-2026-10482",
    fullName = "Alex Morgan",
    passportNumber = "542617843",
    nationality = "United Kingdom",
    gender = "Female",
    dob = "14 May 1992",
    stay = "The Park, New Delhi",
    visaType = "e-Tourist Visa (30 Days)",
    applicationType = "Tourist / Sightseeing",
    issueDate = "26 Aug 2026",
    expiryDate = "25 Sep 2026",
    entries = "Double Entry",
    status = "GRANTED / APPROVED",
  } = data;

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 12;
  const contentWidth = pageWidth - margin * 2; // 186mm

  // --- Outer Border & Inner Security Border ---
  doc.setDrawColor(210, 218, 212);
  doc.setLineWidth(0.3);
  doc.rect(margin, margin, contentWidth, pageHeight - margin * 2);

  doc.setDrawColor(28, 62, 72);
  doc.setLineWidth(0.7);
  doc.rect(margin + 1.5, margin + 1.5, contentWidth - 3, pageHeight - margin * 2 - 3);

  // Top Tricolor Accent Line
  const tricolorY = margin + 2;
  const segW = (contentWidth - 3) / 3;
  doc.setFillColor(233, 165, 56); // Saffron
  doc.rect(margin + 1.5, tricolorY, segW, 1.8, "F");
  doc.setFillColor(255, 255, 255); // White
  doc.rect(margin + 1.5 + segW, tricolorY, segW, 1.8, "F");
  doc.setFillColor(40, 130, 75); // Green
  doc.rect(margin + 1.5 + segW * 2, tricolorY, segW, 1.8, "F");

  // --- Watermark (Faint diagonal background text) ---
  doc.saveGraphicsState();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(242, 245, 243);
  doc.text("DEMO PROTOTYPE COPY", pageWidth / 2, 135, { align: "center", angle: 45 });
  doc.text("NOT VALID FOR ACTUAL TRAVEL", pageWidth / 2, 165, { align: "center", angle: 45 });
  doc.restoreGraphicsState();

  // --- Header Section ---
  const emblemW = 15;
  const emblemH = 24.8;
  const emblemY = margin + 5;

  try {
    doc.addImage(EMBLEM_BASE64, "PNG", pageWidth / 2 - emblemW / 2, emblemY, emblemW, emblemH);
  } catch {
    // Fallback if image fails
  }

  // Header Titles positioned with proper clearance below emblem
  let currentY = emblemY + emblemH + 6.5;

  doc.setFont("times", "bold");
  doc.setFontSize(14);
  doc.setTextColor(20, 34, 32);
  doc.text("GOVERNMENT OF INDIA", pageWidth / 2, currentY, { align: "center" });

  currentY += 5.0;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(28, 62, 72);
  doc.text("MINISTRY OF HOME AFFAIRS · IMMIGRATION BUREAU", pageWidth / 2, currentY, { align: "center" });

  currentY += 4.2;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(92, 106, 102);
  doc.text("e-Visa Services Division · New Delhi", pageWidth / 2, currentY, { align: "center" });

  // Main Banner Title
  currentY += 4.8;
  const cardX = margin + 6;
  const cardW = contentWidth - 12; // 174mm

  doc.setFillColor(28, 62, 72);
  doc.roundedRect(cardX, currentY, cardW, 8.5, 1.2, 1.2, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text("ELECTRONIC TRAVEL AUTHORISATION (ETA)", pageWidth / 2, currentY + 5.8, { align: "center" });

  // Prototype Notice Box
  currentY += 11.5;
  doc.setFillColor(254, 248, 238);
  doc.setDrawColor(233, 165, 56);
  doc.setLineWidth(0.3);
  doc.roundedRect(cardX, currentY, cardW, 7.5, 1, 1, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(168, 96, 16);
  doc.text("NOTICE:", cardX + 3.5, currentY + 4.8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.8);
  doc.setTextColor(80, 80, 80);
  doc.text("This document is generated by an independent prototype. All data shown is simulated for demo purposes.", cardX + 16.5, currentY + 4.8);

  // --- Status & Reference Section Card ---
  currentY += 10.5;
  const statusCardH = 28;
  doc.setFillColor(246, 249, 247);
  doc.setDrawColor(198, 212, 204);
  doc.roundedRect(cardX, currentY, cardW, statusCardH, 1.2, 1.2, "FD");

  // Status Badge
  doc.setFillColor(32, 122, 66);
  doc.roundedRect(cardX + 4, currentY + 4, 38, 7, 1, 1, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(255, 255, 255);
  doc.text(`STATUS: ${status.replace(" / ", " ")}`, cardX + 23, currentY + 8.8, { align: "center" });

  // Reference IDs
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(96, 112, 108);
  doc.text("APPLICATION ID:", cardX + 50, currentY + 7);
  doc.text("ETA NUMBER:", cardX + 112, currentY + 7);

  doc.setFont("courier", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(20, 34, 32);
  doc.text(applicationId, cardX + 50, currentY + 11.5);
  doc.text("IN26ETV00928341", cardX + 112, currentY + 11.5);

  // Internal Divider
  doc.setDrawColor(218, 226, 222);
  doc.line(cardX + 4, currentY + 15, cardX + cardW - 4, currentY + 15);

  // Status Meta Row
  const metaY = currentY + 20;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(110, 122, 118);
  doc.text("VISA SERVICE / TYPE", cardX + 4, metaY);
  doc.text("NO. OF ENTRIES", cardX + 64, metaY);
  doc.text("DATE OF ISSUE", cardX + 108, metaY);
  doc.text("VALID UNTIL", cardX + 144, metaY);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(20, 34, 32);
  doc.text(visaType, cardX + 4, metaY + 4.5);
  doc.text(entries, cardX + 64, metaY + 4.5);
  doc.text(issueDate, cardX + 108, metaY + 4.5);
  doc.text(expiryDate, cardX + 144, metaY + 4.5);

  // --- Applicant Particulars Section ---
  currentY += statusCardH + 5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(28, 62, 72);
  doc.text("APPLICANT PARTICULARS", cardX, currentY);

  currentY += 3;
  const tableH = 46;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(198, 212, 204);
  doc.roundedRect(cardX, currentY, cardW, tableH, 1.2, 1.2, "FD");

  const rows = [
    { l1: "Full Name (as in Passport):", v1: fullName.toUpperCase(), l2: "Passport Number:", v2: passportNumber },
    { l1: "Nationality / Citizenship:", v1: nationality, l2: "Date of Birth:", v2: dob },
    { l1: "Gender:", v1: gender.includes("/") ? gender : `${gender} / Adult`, l2: "Place of Issue:", v2: nationality },
    { l1: "Address / Stay in India:", v1: stay, l2: "Application Type:", v2: applicationType },
    { l1: "Permitted Ports of Entry:", v1: "28 Designated Airports & 5 Designated Seaports in India", l2: "", v2: "" },
  ];

  let rY = currentY + 5.5;
  rows.forEach((r, idx) => {
    if (idx % 2 === 1) {
      doc.setFillColor(249, 251, 250);
      doc.rect(cardX + 0.4, rY - 4.2, cardW - 0.8, 8.8, "F");
    }

    // Left Column
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(100, 112, 108);
    doc.text(r.l1, cardX + 3.5, rY);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(20, 34, 32);
    doc.text(r.v1, cardX + 44, rY);

    // Right Column
    if (r.l2) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(100, 112, 108);
      doc.text(r.l2, cardX + 98, rY);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(20, 34, 32);
      doc.text(r.v2, cardX + 130, rY);
    }

    rY += 8.8;
  });

  // --- Security QR Code & Verification Stamp Card ---
  currentY += tableH + 5;
  const secH = 33;
  doc.setFillColor(246, 249, 247);
  doc.setDrawColor(198, 212, 204);
  doc.roundedRect(cardX, currentY, cardW, secH, 1.2, 1.2, "FD");

  // QR Code Matrix Vector
  const qrX = cardX + 4;
  const qrY = currentY + 3.5;
  const qrSize = 26;

  doc.setFillColor(255, 255, 255);
  doc.rect(qrX, qrY, qrSize, qrSize, "F");
  doc.setDrawColor(40, 50, 48);
  doc.setLineWidth(0.2);
  doc.rect(qrX, qrY, qrSize, qrSize);

  const drawFinder = (fx: number, fy: number) => {
    doc.setFillColor(20, 34, 32);
    doc.rect(fx, fy, 7, 7, "F");
    doc.setFillColor(255, 255, 255);
    doc.rect(fx + 1.2, fy + 1.2, 4.6, 4.6, "F");
    doc.setFillColor(20, 34, 32);
    doc.rect(fx + 2.3, fy + 2.3, 2.4, 2.4, "F");
  };
  drawFinder(qrX + 1.5, qrY + 1.5);
  drawFinder(qrX + qrSize - 8.5, qrY + 1.5);
  drawFinder(qrX + 1.5, qrY + qrSize - 8.5);

  doc.setFillColor(20, 34, 32);
  for (let r = 0; r < 5; r++) {
    for (let c = 0; c < 5; c++) {
      if ((r + c * 3) % 2 === 0) doc.rect(qrX + 10.5 + c * 1.5, qrY + 3 + r * 1.5, 1.2, 1.2, "F");
      if ((r * 2 + c) % 3 === 0) doc.rect(qrX + 3 + c * 1.5, qrY + 11 + r * 1.5, 1.2, 1.2, "F");
      if ((r + c) % 2 === 1) doc.rect(qrX + 11 + c * 1.5, qrY + 13 + r * 1.5, 1.2, 1.2, "F");
    }
  }

  // QR Info Text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(28, 62, 72);
  doc.text("IMMIGRATION BUREAU QR ENCRYPTION", qrX + qrSize + 5, currentY + 7.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.8);
  doc.setTextColor(90, 102, 98);
  doc.text(`Digital Signature: SHA256-IN-ETA-${applicationId}`, qrX + qrSize + 5, currentY + 12);
  doc.text("Scan upon arrival at Indian Immigration Counter for verification.", qrX + qrSize + 5, currentY + 16.5);
  doc.text("Online Verification: https://indianvisaonline.gov.in/evisa/StatusEnquiry", qrX + qrSize + 5, currentY + 21);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 62, 72);
  doc.text("Biometrics mandatory upon arrival.", qrX + qrSize + 5, currentY + 25.5);

  // Official Seal Stamp (No overlapping text, no broken unicode characters)
  const sealX = cardX + cardW - 20;
  const sealY = currentY + 16.5;

  doc.setDrawColor(180, 106, 20);
  doc.setLineWidth(0.5);
  doc.circle(sealX, sealY, 11);
  doc.setLineWidth(0.2);
  doc.circle(sealX, sealY, 9.6);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(4.2);
  doc.setTextColor(180, 106, 20);
  doc.text("IMMIGRATION BUREAU", sealX, sealY - 4.4, { align: "center" });

  doc.setFillColor(254, 246, 230);
  doc.setDrawColor(180, 106, 20);
  doc.setLineWidth(0.25);
  doc.roundedRect(sealX - 8, sealY - 2, 16, 4, 0.6, 0.6, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(5);
  doc.setTextColor(180, 106, 20);
  doc.text("VERIFIED", sealX, sealY + 0.9, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(4);
  doc.text("GOVERNMENT OF INDIA", sealX, sealY + 5.8, { align: "center" });

  // --- Important Instructions for the Traveler ---
  currentY += secH + 4.5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(28, 62, 72);
  doc.text("IMPORTANT INSTRUCTIONS FOR THE TRAVELER", cardX, currentY);

  currentY += 4;
  const instructions = [
    "1. You MUST carry a physical printed copy of this Electronic Travel Authorisation (ETA) along with your original passport.",
    "2. Passport must have at least six (6) months validity from the date of arrival in India and contain at least two blank pages.",
    "3. Biometrics (fingerprints & facial photograph) of the applicant will be mandatorily captured upon arrival at Immigration in India.",
    `4. The ${visaType.split(" (")[0]} is non-extendable, non-convertible and is not valid for visiting Protected / Restricted / Cantonment areas.`,
    "5. The validity of the e-Visa starts from the date of first arrival or granted issue window in India.",
    "6. For 24x7 e-Visa official assistance: indian-evisa@gov.in | Helpdesk Phone: +91-11-24300666.",
  ];

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.6);
  doc.setTextColor(60, 72, 68);

  instructions.forEach((inst) => {
    doc.text(inst, cardX, currentY);
    currentY += 3.8;
  });

  // --- Bottom Footer Bar ---
  const footerY = pageHeight - margin - 5;
  doc.setDrawColor(210, 220, 215);
  doc.setLineWidth(0.3);
  doc.line(cardX, footerY - 2, cardX + cardW, footerY - 2);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(130, 142, 138);
  doc.text("Page 1 of 1  ·  Official Prototype Generation  ·  Ministry of Home Affairs, Government of India", cardX, footerY + 2);
  doc.text(`Ref: ${applicationId}-P26`, cardX + cardW, footerY + 2, { align: "right" });

  // Save the valid PDF in browser environment
  if (typeof window !== "undefined") {
    doc.save(`India-eVisa-ETA-${applicationId}.pdf`);
  }

  return doc;
}
